version: '3.8'
services:
    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb-local
        ports:
            - "8000:8000"
        volumes:
            - "./docker/dynamodb:/home/dynamodblocal/data"
        working_dir: /home/dynamodblocal

    localstack:
        image: "localstack/localstack:latest"
        container_name: localstack
        ports:
            - "4566:4566"
            - "4510-4559:4510-4559"

        environment:
            - DEBUG=1
            # See: Persistence Mechanism | Docs: https://docs.localstack.cloud/localstack/persistence-mechanism/
            - PERSISTENCE=0 # If you changed this to "1", then you may wish to set volume (see "volumes" key below).
            - DISABLE_CORS_CHECKS=1
            - DYNAMODB_SHARE_DB=1 # When activated, DynamodDB will use a single database instead of separate databases for each credential and region.
