[tool.poetry]
name = "ack-code"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
boto3 = "~1.40.3"
mypy-boto3-dynamodb = "^1.40.0"
freezegun      = "^1.5.4"
moto           = "^4"
coverage = "^7.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
