name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml

jobs:
  - job: teardown
    displayName: PR Teardown
    timeoutInMinutes: 30
    pool:
      name: 'AWS-ECS'
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - bash: |
          echo $(action_pr_number)
          WORKSPACE="pr-"$(ACTION_PR_NUMBER)
          echo $WORKSPACE
          echo "##vso[task.setvariable variable=WORKSPACE]$WORKSPACE"
          echo "##vso[task.setvariable variable=ACTION_PR_NUMBER]$(ACTION_PR_NUMBER)"
        displayName: Set workspace tag

      - template: ./templates/aws-assume-role.yml
        parameters:
            role: "auto-ops"
            profile: "apim-dev"
            aws_account: "dev"

      - bash: |
          echo "##vso[task.setvariable variable=AWS_DEFAULT_REGION]eu-west-2"
          echo "##vso[task.setvariable variable=APIGEE_ENVIRONMENT]internal-dev"
        displayName: Set AWS default region and Terraform state bucket

      - bash: |
          export AWS_PROFILE=apim-dev
          account_id="$(aws sts get-caller-identity --query Account --output text)"

          cd terraform
          terraform workspace select $(WORKSPACE)
          make init && make destroy aws_account_no=${account_id} environment=$(WORKSPACE)
        displayName: Destroy terraform PR workspace and linked resources
        retryCountOnTaskFailure: 2