name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Immunisation-Fhir-Api-Build"
    trigger:
      branches:
        include:
          - release-*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_requires_approval: true
    prod_producer_approval: true
    apigee_deployments:
      - environment: prod
        stage_name: blue
        jinja_templates:
          DOMAIN_ENDPOINT: https://blue.imms.prod.vds.platform.nhs.uk
      - environment: prod
        stage_name: green
        jinja_templates:
          DOMAIN_ENDPOINT: https://green.imms.prod.vds.platform.nhs.uk
