name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "Immunisation-Fhir-Api-Build"

pool:
  name: "AWS-ECS"

variables:
  - template: project.yml

parameters:
  - name: sub_environment
    displayName: Sub-Environment
    type: string
    default: blue
    values:
      - blue
      - green

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_requires_approval: true
    prod_producer_approval: true
    apigee_deployments:
      - environment: prod
        depends_on: []
        jinja_templates:
          DOMAIN_ENDPOINT: https://${{ parameters.sub_environment }}.imms.prod.vds.platform.nhs.uk
