name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml

jobs:
  - job: teardown
    displayName: PR Teardown
    timeoutInMinutes: 30
    pool:
      name: 'AWS-ECS'
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - bash: |
          echo $(action_pr_number)
          WORKSPACE="pr-"$(ACTION_PR_NUMBER)
          echo $WORKSPACE
          echo "##vso[task.setvariable variable=WORKSPACE]$WORKSPACE"
          echo "##vso[task.setvariable variable=ACTION_PR_NUMBER]$(ACTION_PR_NUMBER)"
        displayName: Set workspace tag

      - template: ./templates/aws-assume-role.yml
        parameters:
            role: "auto-ops"
            profile: "apim-dev"
            aws_account: "dev"

      - bash: |
          echo "##vso[task.setvariable variable=AWS_DEFAULT_REGION]eu-west-2"
          echo "##vso[task.setvariable variable=APIGEE_ENVIRONMENT]internal-dev"
        displayName: Set AWS default region and Terraform state bucket

      - bash: |
          export AWS_PROFILE=apim-dev
          account_id="$(aws sts get-caller-identity --query Account --output text)"

          export environment="internal-dev"
          export sub_environment="$(WORKSPACE)"

          echo "Checking if bucket immunisation-${sub_environment}-terraform-state-files exists..."
          BUCKET_NAME="immunisation-${sub_environment}-terraform-state-files"
          FALLBACK_BUCKET_NAME="immunisation-internal-dev-terraform-state-files"

          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket $BUCKET_NAME does NOT exist. Falling back to internal-dev for init only..."
            export ENVIRONMENT="internal-dev"
            export BUCKET_NAME="$FALLBACK_BUCKET_NAME"
          else
            export ENVIRONMENT="$environment"
            export BUCKET_NAME="$BUCKET_NAME"
          cd terraform
          make init

          export ENVIRONMENT="$sub_environment"
          export BUCKET_NAME="immunisation-${sub_environment}-terraform-state-files"

          cd terraform
          make workspace sub_environment=$sub_environment
          make destroy sub_environment=$sub_environment aws_account_no=${account_id}
        displayName: Destroy terraform PR workspace and linked resources
        retryCountOnTaskFailure: 2
