# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/ack_backend"
      - "/delta_backend"
      - "/filenameprocessor"
      - "/grafana/non-prod/docker"
      - "/mesh_processor"
      - "/recordprocessor"
      - "/sandbox"
      - "/temporary_sandbox"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      docker-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/ack_backend"
      - "/backend"
      - "/delta_backend"
      - "/e2e"
      - "/e2e_batch"
      - "/filenameprocessor"
      - "/mesh_processor"
      - "/recordprocessor"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "terraform"
    directories:
      - "/grafana/non-prod/terraform"
      - "/infra"
      - "/mesh-infra"
      - "/terraform"
      - "/terraform_aws_backup/**"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      terraform-minor-patch:
        update-types:
          - "minor"
          - "patch"
