line-length = 121
target-version = "py311"

[lint]
# TODO - consider enabling more rulesets, e.g. B, C90, I, N, RET, S, UP
select = ["E", "F", "W"]
# Recommended exclusions as per the docs, plus E501 line-too-long
ignore = ["E111", "E114", "E117", "E501", "W191"]
