src = ["."]
line-length = 121

[lint]
# TODO - consider enabling more rulesets, e.g. B, C90, N, RET, S, UP
select = ["E", "F", "I", "W"]
# Recommended exclusions as per the docs, plus E501 line-too-long
ignore = ["E111", "E114", "E117", "E501", "W191"]
