imms_account_id          = "084828561157"
dspp_account_id          = "603871901111"
admin_role               = "" # We shouldn't be using the root account. There should be an Admin role
dev_ops_role             = ""
auto_ops_role            = "role/auto-ops"
dspp_admin_role          = "root"
environment              = "prod"
parent_route53_zone_name = "imms.dev.vds.platform.nhs.uk" # TBC for prod might be blue/green
child_route53_zone_name  = "imms.dev.vds.platform.nhs.uk" # TBC for prod might be blue/green
