trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
      
stages:
  - stage: GreenDeploy
    displayName: "Deploy to Green"
    jobs:
      - template: templates/deploy-int-job.yml
        parameters:
          tf_environment: green
          tf_dir: "terraform_old"
  # - stage: BlueDeploy
  #   displayName: "Deploy to Blue"
  #   dependsOn: GreenDeploy
  #   jobs:
  #     - template: templates/deploy-int-job.yml
  #       parameters:
  #         tf_environment: blue
  #         tf_dir: "terraform_old"

      
