# This is an OpenAPI Specification (https://swagger.io/specification/)
# for immunisation-fhir-api owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'immunisation-fhir-api'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview
    Add a fully fledged description here with markdown syntax.
    For help completing the content of your API spec, see our guidance on the minimum standard (bronze) details 
    to include [here](https://nhsd-confluence.digital.nhs.uk/display/APM/Writing+a+bronze+API+cover+page). You should also base your content on our exemplar API - [PDS FHIR](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir).
    ## Who can use this API
    To be completed.
    ## Related APIs
    To be completed.
    ## API status and roadmap
    To be completed.
    ## Service level
    To be completed.
    ## Technology
    To be completed.
    ## Network access
    To be completed.
    ## Security and authorisation
    To be completed.
    ## Environments and testing
    To be completed.
    ## Onboarding
    To be completed.
  contact:
    name: 'immunisation-fhir-api API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/immunisation-fhir-api'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/immunisation-fhir-api'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/immunisation-fhir-api'
    description: Production environment.
paths:
  /immunisation/{id}:
    get:
      summary: Get Immunisation record event by ID
      description: Retrieves immunisation record event details by ID.
      parameters:
        - name: id
          description: ID of the immunisation
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: c3f6145e-1a26-4345-b3f2-dccbcba62049
        - name: X-Correlation-Id
          description: ID of the immunisation
          in: header
          required: true
          schema:
            type: string
            format: uuid
            example: c3f6145e-1a26-4345-b3f2-dccbcba62049
        - name: X-Request-Id
          description: ID of the immunisation
          in: header
          required: true
          schema:
            type: string
            format: uuid
            example: c3f6145e-1a26-4345-b3f2-dccbcba62049
      responses:
        '200':
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                $ref: examples/id/GET-success.json
          headers:
            X-Correlation-Id:
              description: 'The X-Correlation-Id from the request header, if supplied, mirrored back.'
              schema:
                type: string
                format: uuid
                example: 9562466f-c982-4bd5-bb0e-255e9f5e6689
            X-Request-Id:
              description: 'The X-Request-Id from the request header, if supplied, mirrored back.'
              schema:
                type: string
                format: uuid
                example: c1ab3fba-6bae-4ba4-b257-5a87c44d4a91
        4XX:
          $ref: '#/components/responses/4XX-imms'  
components:
  parameters:
    ID:
      name: immunisation-record
      description: |
        A unique immunisation record ID.
      required: True
      in: path
      schema:
        type: string
        example: "http://example.com/immunisation/{id}"
  responses:
    4XX-imms:
      description: |
        Below are examples of potential HTTP status codes and their associated error codes, which could be returned in the event of a fault. 

        | HTTP status | Error code                 | Description |
        | ----------- | -------------------------- | --------------------------------------------- |
        | 400         | INVALID                    | The provided event ID is either missing or not in the expected format. |
        | 404         | NOT-FOUND                  | The requested resource was not found. |

      content:
        application/fhir+json:
          schema:
            $ref: '#/components/schemas/OperationOutcome'
          example:
            {
  "resourceType": "OperationOutcome",
  "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
  "meta": {
    "profile": [
      "https://simplifier.net/guide/UKCoreDevelopment2/ProfileUKCore-OperationOutcome"
    ]
  },
  "issue": [
    {
      "severity": "error",
      "code": "invalid",
      "details": {
        "coding": [
          {
            "system": "https://fhir.nhs.uk/Codesystem/http-error-codes",
            "code": "INVALID"
          }
        ]
      },
      "diagnostics": "The provided event ID is either missing or not in the expected format."
    }
  ]
}
      headers:
        ID:
          description: 'The immunisation record Id from the request header, if supplied, mirrored back.'
          schema:
            type: string
            format: uuid
            example: 7364896f-h736-7ju8-fr0e-576r585f1083
        X-Correlation-Id:
          description: 'The X-Correlation-Id from the request header, if supplied, mirrored back.'
          schema:
            type: string
            format: uuid
            example: 9562466f-c982-4bd5-bb0e-255e9f5e6689
        X-Request-Id:
          description: 'The X-Request-Id from the request header, if supplied, mirrored back.'
          schema:
            type: string
            format: uuid
            example: c1ab3fba-6bae-4ba4-b257-5a87c44d4a91       
  schemas:
    OperationOutcome:
      $ref: schemas/OperationOutcome.yaml
