openapi: 3.0.0
info:
  title: Immunisation FHIR API
  description: Immunisation FHIR API
  version: 0.1.0
paths:
  /event:
    get:
      x-amazon-apigateway-integration:
        uri: "${get_event.lambda_arn}"
        payloadFormatVersion: "1.0"
        passthroughBehavior: "when_no_match"
        httpMethod: "GET"
        timeoutInMillis: 30000
        type: "AWS_PROXY"
      responses:
        '200':
          description: An Immunisation event
          content:
            application/json:
              schema:
                type: object
    post:
      x-amazon-apigateway-integration:
        uri: "${post_event.lambda_arn}"
        payloadFormatVersion: "1.0"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        timeoutInMillis: 30000
        type: "AWS_PROXY"
      responses:
        '200':
          description: An Immunisation event
          content:
            application/json:
              schema:
                type: object
