# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  
datasources:
  - name: DS_CLOUDWATCH                     # name of the datasource
    type: cloudwatch                        # type of the data source
    access: proxy                           # make grafana perform the requests
    org_id: 1                               # id of the organization to tie this datasource to
    url: ''                                 # url of the instance
    password:                               # <string> database password, if used
    user:                                   # <string> database user, if used
    database:                               # <string> database name, if used
    basicAuth: false                        # <bool> enable/disable basic auth
    basicAuthUser:                          # <string> basic auth username, if used
    basicAuthPassword:                      # <string> basic auth password, if used
    withCredentials: false                  # <bool> enable/disable with credentials headers
    isDefault: true                         # <bool> mark as default datasource. Max one per org
    jsonData:                               # <map> fields that will be converted to json and stored in json_data
      authType: keys
      defaultRegion: eu-west-2
    editable: true                          # whether it should be editable
    version: 1
  
  
  - name: 'Prometheus'                    # name of the datasource
    type: 'prometheus'                    # type of the data source
    access: 'proxy'                       # make grafana perform the requests
    org_id: 1                             # id of the organization to tie this datasource to
    url: 'http://prometheus:9090'         # url of the prom instance
    password:                             # <string> database password, if used
    user:                                 # <string> database user, if used
    database:                             # <string> database name, if used
    basicAuth: false                      # <bool> enable/disable basic auth
    basicAuthUser:                        # <string> basic auth username, if used
    basicAuthPassword:                    # <string> basic auth password, if used
    withCredentials:                      # <bool> enable/disable with credentials headers
    isDefault: false                       # <bool> mark as default datasource. Max one per org
    jsonData:                             # <map> fields that will be converted to json and stored in json_data
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:                       # <string> json object of data that will be encrypted.
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    editable: true                        # whether it should be editable
    version: 1

  - name: 'Loki'                          # name of the datasource
    type: 'loki'                          # type of the data source
    access: 'proxy'                       # make grafana perform the requests
    org_id: 1                             # id of the organization to tie this datasource to
    url: 'http://loki:3100'               # url of the instance
    password:                             # <string> database password, if used
    user:                                 # <string> database user, if used
    database:                             # <string> database name, if used
    basicAuth: false                      # <bool> enable/disable basic auth
    basicAuthUser:                        # <string> basic auth username, if used
    basicAuthPassword:                    # <string> basic auth password, if used
    withCredentials:                      # <bool> enable/disable with credentials headers
    isDefault: false                       # <bool> mark as default datasource. Max one per org
    jsonData:                             # <map> fields that will be converted to json and stored in json_data
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:                       # <string> json object of data that will be encrypted.
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    editable: true                        # whether it should be editable
    version: 1


