steps:
  - bash: |
      #BUILDKIT_PROGRESS=plain docker build --target test -t imms-lambda-build .

    displayName: Test lambda code
    workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/lambda_code"
  - bash: |
      mkdir -p build
      npm run publish 2> /dev/null
      cp build/immunisation-fhir-api.json sandbox/

        cd sandbox
      docker build -t sandbox .
    displayName: Build sandbox image
    workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)"
