parameters:
  - name: service_name
    type: string
    default: 'immunisation-fhir-api'
  - name: short_service_name
    type: string
    default: 'ifa'

stages:
  - stage: Prod_Green_Deployment
    jobs:
      - template: deploy-manual-approval.yml
  
      - template: deploy-stage.yml
        parameters:
          service_name: ${{ parameters.service_name }}
          short_service_name: ${{ parameters.short_service_name }}
          environment: prod
          post_init:
              - template: post-prod-deploy.yml
                parameters:
                  aws_account_type: 'prod'
                  deployment_type: 'green'
  - stage: Prod_Blue_Deployment
    jobs:
      - template: deploy-manual-approval.yml
  
      - template: deploy-stage.yml
        parameters:
          service_name: ${{ parameters.service_name }}
          short_service_name: ${{ parameters.short_service_name }}
          environment: prod
          post_init:
              - template: post-prod-deploy.yml
                parameters:
                  aws_account_type: 'prod'
                  deployment_type: 'blue'