lint-fix:
	poetry run ruff check --fix --extend-exclude tests/e2e_automation/ ..

lint:
	poetry run ruff check --extend-exclude tests/e2e_automation/ ..

format:
	poetry run ruff format --exclude tests/e2e_automation/ ..

format-check:
	poetry run ruff format --check --exclude tests/e2e_automation/ ..
