[project]
name = "mesh-code"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "<you@example.com>" }]
readme = "README.md"

[tool.poetry]
package-mode = false
packages    = [{include = "src"}]

[tool.poetry.dependencies]
python = "~3.10"
boto3 = "~1.26.90"
mypy-boto3-dynamodb = "^1.26.164"
moto = "~4.2.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
