version: '3.8'

services:
    localstack:
        container_name: "localstack_main"
        image: localstack/localstack:latest
        environment:
            - SERVICES=s3,dynamodb,sts
            - DEFAULT_REGION=eu-west-2
            - DEBUG=1
            - PERSISTENCE=1
        ports:
            - "4566:4566"
        volumes:
            - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
