import os

AUDIT_TABLE_FILENAME_GSI = os.getenv("FILE_NAME_GSI")
AUDIT_TABLE_QUEUE_NAME_GSI = os.getenv("QUEUE_NAME_GSI")
QUEUE_URL = os.getenv("QUEUE_URL")
SPLUNK_FIREHOSE_STREAM_NAME = os.getenv("SPLUNK_FIREHOSE_NAME")
