# Comma-separated header string for building CSV test rows

CSV_HEADER = (
    "NHS_NUMBER,PERSON_FORENAME,PERSON_SURNAME,SITE_CODE,"
    "PERFORMING_PROFESSIONAL_FORENAME,PERFORMING_PROFESSIONAL_SURNAME,PRIMARY_SOURCE,"
    "VACCINATION_PROCEDURE_CODE,VACCINATION_PROCEDURE_TERM,DOSE_SEQUENCE,"
    "VACCINE_PRODUCT_CODE,VACCINE_PRODUCT_TERM,VACCINE_MANUFACTURER,BATCH_NUMBER"
)


# Sample CSV values for testing
CSV_VALUES = {
    "NHS_NUMBER": "9000000009",
    "PERSON_FORENAME": "JOHN",
    "PERSON_SURNAME": "DOE",
    "SITE_CODE": "RJ1",
    "PERFORMING_PROFESSIONAL_FORENAME": "ALICE",
    "PERFORMING_PROFESSIONAL_SURNAME": "SMITH",
    "PRIMARY_SOURCE": "true",
    "VACCINATION_PROCEDURE_CODE": "PROC123",
    "VACCINATION_PROCEDURE_TERM": "Procedure Term",
    "DOSE_SEQUENCE": 1,
    "VACCINE_PRODUCT_CODE": "VACC123",
    "VACCINE_PRODUCT_TERM": "Vaccine Term",
    "VACCINE_MANUFACTURER": "Manufacturer XYZ",
    "BATCH_NUMBER": "BATCH001",
}
