# Comma-separated header string for building CSV test rows

CSV_HEADER = (
    "NHS_NUMBER,PERSON_FORENAME,PERSON_SURNAME,PERSON_DOB,PERSON_GENDER_CODE,PERSON_POSTCODE,DATE_AND_TIME,SITE_CODE,"
    "SITE_CODE_TYPE_URI,UNIQUE_ID,UNIQUE_ID_URI,ACTION_FLAG,PERFORMING_PROFESSIONAL_FORENAME,PERFORMING_PROFESSIONAL_SURNAME,RECORDED_DATE,"
    "PRIMARY_SOURCE,VACCINATION_PROCEDURE_CODE,VACCINATION_PROCEDURE_TERM,DOSE_SEQUENCE,"
    "VACCINE_PRODUCT_CODE,VACCINE_PRODUCT_TERM,VACCINE_MANUFACTURER,BATCH_NUMBER,EXPIRY_DATE,SITE_OF_VACCINATION_CODE,SITE_OF_VACCINATION_TERM,"
    "ROUTE_OF_VACCINATION_CODE,ROUTE_OF_VACCINATION_TERM,DOSE_AMOUNT,DOSE_UNIT_CODE,DOSE_UNIT_TERM,INDICATION_CODE,LOCATION_CODE,LOCATION_CODE_TYPE_URI"
)


# Sample CSV values for testing
CSV_VALUES = {
    "NHS_NUMBER": "9000000009",
    "PERSON_FORENAME": ["JOHN"],
    "PERSON_SURNAME": "DOE",
    "PERSON_DOB": "1980-01-01",
    "PERSON_GENDER_CODE": "M",
    "PERSON_POSTCODE": "AB12 3CD",
    "DATE_AND_TIME": "20250306T13281701",
    "SITE_CODE": "RJ1",
    "SITE_CODE_TYPE_URI": "https://fhir.nhs.uk/Id/ods-organization-code",
    "UNIQUE_ID": "ACME-vacc123456",
    "UNIQUE_ID_URI": "https://supplierABC/identifiers/vacc",
    "ACTION_FLAG": "UPDATE",
    "PERFORMING_PROFESSIONAL_FORENAME": "ALICE",
    "PERFORMING_PROFESSIONAL_SURNAME": "SMITH",
    "RECORDED_DATE": "20250306",
    "PRIMARY_SOURCE": "true",
    "VACCINATION_PROCEDURE_CODE": "PROC123",
    "VACCINATION_PROCEDURE_TERM": "Procedure Term",
    "DOSE_SEQUENCE": "1",
    "VACCINE_PRODUCT_CODE": "VACC123",
    "VACCINE_PRODUCT_TERM": "Vaccine Term",
    "VACCINE_MANUFACTURER": "Manufacturer XYZ",
    "BATCH_NUMBER": "BATCH001",
    "EXPIRY_DATE": "20250702",
    "SITE_OF_VACCINATION_CODE": "368208006",
    "SITE_OF_VACCINATION_TERM": "Left upper arm structure (body structure)",
    "ROUTE_OF_VACCINATION_CODE": "78421000",
    "ROUTE_OF_VACCINATION_TERM": "Intramuscular route (qualifier value)",
    "DOSE_AMOUNT": "0.5",
    "DOSE_UNIT_CODE": "ml",
    "DOSE_UNIT_TERM": "milliliter",
    "INDICATION_CODE": "443684005",
    "LOCATION_CODE": "X99999",
    "LOCATION_CODE_TYPE_URI": "https://fhir.nhs.uk/Id/ods-organization-code",
}


CSV_DELIMITER_SAMPLE = """NHS_NUMBER|PERSON_FORENAME|PERSON_SURNAME|PERSON_DOB|PERSON_GENDER_CODE|PERSON_POSTCODE|DATE_AND_TIME|SITE_CODE|SITE_CODE_TYPE_URI|UNIQUE_ID|UNIQUE_ID_URI|ACTION_FLAG|PERFORMING_PROFESSIONAL_FORENAME|PERFORMING_PROFESSIONAL_SURNAME|RECORDED_DATE|PRIMARY_SOURCE|VACCINATION_PROCEDURE_CODE|VACCINATION_PROCEDURE_TERM|DOSE_SEQUENCE|VACCINE_PRODUCT_CODE|VACCINE_PRODUCT_TERM|VACCINE_MANUFACTURER|BATCH_NUMBER|EXPIRY_DATE|SITE_OF_VACCINATION_CODE|SITE_OF_VACCINATION_TERM|ROUTE_OF_VACCINATION_CODE|ROUTE_OF_VACCINATION_TERM|DOSE_AMOUNT|DOSE_UNIT_CODE|DOSE_UNIT_TERM|INDICATION_CODE|LOCATION_CODE|LOCATION_CODE_TYPE_URI
9990548609|Emily|Watson|19870214|2|WF8 4ED|20250306T13281701|B0C4P|https://fhir.hl7.org.uk/Id/urn-school-number|ACME-vacc123456|https://supplierABC/identifiers/vacc|UPDATE|Darren Official|Furlong Official|20250306|956951000000104|Seasonal influenza vaccination (procedure)|2|39114911000001104|COVID-19 Vaccine Vaxzevria (ChAdOx1 S [recombinant]) 0.5ml dose suspension (AstraZeneca)|AstraZeneca Ltd|4120Z001|20250702|368208006|Left upper arm structure (body structure)|78421000|Intramuscular route (qualifier value)|0.5||milliliter|443684005|X99999|https://fhir.nhs.uk/Id/ods-organization-code|[]
9990548617|James|Turner|19911230|1|WF8 4ED|20250306T14203001|B0C4P|https://fhir.hl7.org.uk/Id/urn-school-number|ACME-vacc123456|https://supplierABC/identifiers/vacc|UPDATE|Tessy Official|Pat Official|20250306||956951000000104|Seasonal influenza vaccination (procedure)|1|39114911000001104|COVID-19 Vaccine Vaxzevria (ChAdOx1 S [recombinant]) 0.5ml dose suspension (AstraZeneca)|AstraZeneca Ltd|4120Z002|20250702|368208006|Left upper arm structure (body structure)|78421000|Intramuscular route (qualifier value)|0.5||milliliter|443684005|X99999|https://fhir.nhs.uk/Id/ods-organization-code|[]
"""
