variable "prefix" {}
variable "short_prefix" {}
variable "zone_id" {}
variable "api_domain_name" {}
variable "environment" {}
variable "sub_environment" {}
variable "oas" {}
variable "aws_region" {}
variable "immunisation_account_id" {}
