name: Deploy Blue Green - INT

on:
  push:
    branches:
      - release-2025-07-25

jobs:
  deploy-green:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: green

  # deploy-blue:
  #   needs: deploy-green
  #   uses: ./.github/workflows/deploy-template.yml
  #   with:
  #     environment: blue