name: Deploy Blue Green - INT

on:
  push:
    branches:
      - release-2025-07-25

jobs:
  deploy-green:
    uses: ./.github/workflows/deploy-template.yml@release-2025-07-25
    with:
      environment: green