name: Deploy Blue Green - INT

on:
  push:
    branches:
      - release-2025-08-12

jobs:
  deploy-green:
    uses: ./.github/workflows/deploy-template.yml
    with:
      apigee_environment: int
      environment: preprod
      sub_environment: int-green
  deploy-blue:
    uses: ./.github/workflows/deploy-template.yml
    with:
      apigee_environment: int
      environment: preprod
      sub_environment: int-blue
