FROM python:3.13-alpine

# Runtime environment variables
# ENV DESC=""
# ENV SOURCE=""
ENV LOGFILE="/logs/logs.txt"
ENV DEPENDENCIES=""



CMD sh -c 'echo "Run unit tests with coverage" >> $LOGFILE'

# RUN mkdir -p /logs

# RUN echo "CWD: $(pwd)" >> $LOGFILE
# RUN echo ">>>>>>>>>>>>> Setting up environment variables: DESC=$DESC, SOURCE=$SOURCE, LOGFILE=$LOGFILE, DEPENDENCIES=$DEPENDENCIES" >> $LOGFILE

# # Install system dependencies
# RUN apk add --no-cache gcc musl-dev

# # Install Poetry
# RUN echo ">>>>>>>>>>>>> Installing Poetry..." >> $LOGFILE
# RUN pip install poetry==1.8.4

# # Set workdir and copy dependency files first for caching
# RUN echo ">>>>>>>>>>>>> Setting up work directory and copying dependency files..." >> $LOGFILE
# WORKDIR /app
# COPY pyproject.toml poetry.lock ./
# RUN poetry install --no-root

# # Copy the rest of the code
# COPY . .

# # Set PYTHONPATH for runtime
# ENV PYTHONPATH=$SOURCE/src:$SOURCE/tests

# # Default command: install dependencies at runtime, then run tests
# CMD sh -c 'if [ -n "$DEPENDENCIES" ]; then pip install $DEPENDENCIES; fi && \
#     echo "Run unit tests with coverage" >> $LOGFILE && \
#     poetry run coverage run --source=$SOURCE -m unittest discover -s $SOURCE || echo "$DESC tests failed" >> /logs/failed_tests.txt && \
#     poetry run coverage xml -o /logs/sonarcloud-coverage-$DESC.xml'
