FROM python:3.11-slim
RUN apt-get update && apt-get install -y gcc  libxml2-dev libxslt-dev libffi-dev
RUN pip install poetry==1.8.4
WORKDIR /app
COPY pyproject.toml poetry.lock ./
COPY pyproject.toml poetry.lock /app/
RUN poetry install --no-root
COPY . .
CMD ["poetry", "run", "python", "-m", "unittest", "discover"]