name: PR Deploy and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-quality-checks:
    uses: ./.github/workflows/quality-checks.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-pr-backend:
    needs: [run-quality-checks]
    if: ${{ always() && !failure() && !cancelled() }}
    uses: ./.github/workflows/deploy-backend.yml
    with:
      apigee_environment: internal-dev
      lambda_build_flags: >-
        ${{ (github.event.action == 'opened' || github.event.action == 'reopened')
            && '{"recordprocessor":true,"ack-backend":true,"mock_pds":true}'
            || '{}' }}
      diff_base_sha: ${{ github.event.action == 'synchronize' && github.event.before || github.event.pull_request.base.sha }}
      diff_head_sha: ${{ github.event.pull_request.head.sha }}
      run_diff_check: ${{ github.event.action == 'synchronize' }}
      create_mns_subscription: true
      environment: dev
      sub_environment: pr-${{github.event.pull_request.number}}

  run-e2e-automation-tests:
    needs: [deploy-pr-backend]
    strategy:
      matrix:
        apigee_environment_name: [internal-dev, internal-dev-sandbox]
        include:
          - apigee_environment_name: internal-dev
            required_test_suite: smoke
          - apigee_environment_name: internal-dev-sandbox
            required_test_suite: sandbox
    uses: ./.github/workflows/run-e2e-automation-tests.yml
    with:
      apigee_environment: ${{ matrix.apigee_environment_name }}
      environment: dev
      sub_environment: pr-${{github.event.pull_request.number}}
      service_under_test: all
      suite_to_run: ${{ matrix.required_test_suite }}
    secrets:
      APIGEE_PASSWORD: ${{ secrets.APIGEE_PASSWORD }}
      APIGEE_BASIC_AUTH_TOKEN: ${{ secrets.APIGEE_BASIC_AUTH_TOKEN }}
      APIGEE_OTP_KEY: ${{ secrets.APIGEE_OTP_KEY }}
      CIS2_E2E_USERNAME: ${{ secrets.CIS2_E2E_USERNAME }}
      STATUS_API_KEY: ${{ secrets.STATUS_API_KEY }}
