name: PR build and test

on:
  push:
    branches: [VED-358-github-actions-for-int]
  workflow_dispatch:

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Debug OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::084828561157:role/auto-ops
          role-session-name: github-actions

      - name: Whoami
        run: aws sts get-caller-identity

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          make init
          
      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          make plan environment=green aws_account_name=int


  # # --- APPROVAL REQUIRED HERE ---
  # manual-approval:
  #   needs: test-oidc
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: int-approval
  #     # protection rules set in GitHub UI will pause here until approval
  #   steps:
  #     - name: Wait for approval
  #       run: echo "Waiting for manual approval..."

  # terraform-apply:
  #   needs: manual-approval
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Terraform Apply
  #       working-directory: ./terraform_old
  #       run: |
  #         make plan environment=green aws_account_name=int
