name: E2E Tests

on:
  push:
    branches: [VED-358-github-actions-for-int]
  workflow_dispatch:

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Debug OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::345594581768:role/auto-ops
          role-session-name: github-actions

      - name: Whoami
        run: aws sts get-caller-identity

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry (from e2e folder)
        working-directory: ./e2e
        run: |
          poetry install --no-root
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          make init
          
      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          make plan environment=internal-dev

      - name: Run e2e
        working-directory: ./e2e
        run: |
          apigee_token=$(aws ssm get-parameter \
            --name "/imms/apigee/non-prod/token" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)

          status_api_key=$(aws ssm get-parameter \
            --name "/imms/apigee/non-prod/status-api-key" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)
          
          export APIGEE_ACCESS_TOKEN=$apigee_token
          export APIGEE_USERNAME=apm-testing-internal-dev@nhs.net
          export APIGEE_ENVIRONMENT=non-prod
          export STATUS_API_KEY=$status_api_key
          export PROXY_NAME=immunisation-fhir-api-internal-dev
          export SERVICE_BASE_PATH=immunisation-fhir-api/FHIR/R4
          export SSO_LOGIN_URL=https://login.apigee.com

          make run
