name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled, opened, synchronize, reopened, unlabeled]
env:
  SCRIPT_FOLDER: ./.github/scripts
  TEST_SCRIPT: $SCRIPT_FOLDER/run_poetry_tests.sh

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: make executable
        run: |
          echo "Making scripts executable:"
          chmod +x $TEST_SCRIPT

      - name: List .github directory
        run: |
          echo "Listing .github directory:"
          ls -la ./.github

      - name: List scripts directory
        run: |
          echo "Listing scripts directory:"
          ls -la ./.github/scripts
          ls -la $SCRIPT_FOLDER

      - name: List all subdirectories (including hidden)
        run: |
          echo "All subdirectories (including hidden):"
          find . -type d

      - name: Check Script Path
        run: |
          echo "TEST_SCRIPT is set to: $TEST_SCRIPT"
          if [ -f "$TEST_SCRIPT" ]; then
            echo "Script exists and is executable."
            ls -l "$TEST_SCRIPT"
          else
            echo "Script does NOT exist at $TEST_SCRIPT"
            # show cwd
            echo "Current working directory:"
            pwd
            # list files in cwd
            echo "Files in current directory:"
            ls -la
            echo "Files in .github directory:"
            ls -la ./.github
            echo "Files in .github/scripts directory:"
            ls -la ./.github/scripts
            exit 1
          fi

      - name: Install poetry
        run: pip install poetry==1.8.4

